name: Update Jorje

on:
  repository_dispatch:
    types:
      - manual-jorje-update
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  jorje:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up JDK
        uses: actions/setup-java@v4.2.2
        with:
          distribution: temurin
          java-version: 11
          cache: gradle
      - name: Run create-jorje-jar.sh
        run: ./packages/apex-ast-serializer/tools/create-jorje-jar.sh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.1.0
        with:
          commit-message: Updated jorje
          title: "Update jorje dependency"
          branch: updates/jorje
          token: ${{ secrets.PERSONAL_TOKEN }}
